server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: authapi
    static_configs:
      - targets: [localhost]
        labels:
          job: auth-api
          app: auth-api
          env: development
          __path__: /var/log/authapi/*.json
    pipeline_stages:
      - json:
          expressions:
            ts: '["@t"]'
            level: '["@l"]'
            msg: '["@m"]'
            cid: CorrelationId
            trace: TraceId
      - labels:
          level:
          app:
          env:
          cid:
      - timestamp:
          source: ts
          format: RFC3339Nano
